services: # 컨테이너 설정
  redis_master:
    container_name: redis_master
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "7010:6379"
  sentinel-1:
    image: 'bitnami/redis-sentinel:latest'
    container_name: sentinel_1
    environment:
      - REDIS_MASTER_SET=mymaster
      - REDIS_MASTER_HOST=127.0.0.1
      - ALLOW_EMPTY_PASSWORD=yes
#      - REDIS_MASTER_PASSWORD=redispassword
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=10000
    depends_on:
      - redis_master
      - redis-slave
    ports:
      - "26379:26379"
  sentinel-2:
    image: 'bitnami/redis-sentinel:latest'
    container_name: sentinel_2
    environment:
      - REDIS_MASTER_SET=mymaster
      - REDIS_MASTER_HOST=127.0.0.1
      - ALLOW_EMPTY_PASSWORD=yes
#      - REDIS_MASTER_PASSWORD=redispassword
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=10000
    depends_on:
      - redis_master
      - redis-slave
    ports:
      - "26380:26379"
  sentinel-3:
    image: 'bitnami/redis-sentinel:latest'
    container_name: sentinel_3
    environment:
      - REDIS_MASTER_SET=mymaster
      - REDIS_MASTER_HOST=127.0.0.1
      - ALLOW_EMPTY_PASSWORD=yes
#      - REDIS_MASTER_PASSWORD=redispassword
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=10000
    depends_on:
      - redis_master
      - redis-slave
    ports:
      - "26381:26379"