server:
  port: 8081
  tomcat:
    threads:
      max: 500
spring:
  config:
    import: oauth2.yml
#  redis:
#    sentinel:
#      master: redis_master
#      nodes:
#        - localhost:26379
#        - localhost:26380
#        - localhost:26381
  datasource:
    url: jdbc:mysql://localhost:3306/redis?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
#    generate-ddl: true
#    show-sql: true
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE